

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nameless
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        tambahStaffBtn.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutBtn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tambahStaffBtn = new javax.swing.JButton();
        tambahMobilBtn = new javax.swing.JButton();
        pinjamMobilBtn = new javax.swing.JButton();
        PengembalianMobilBtn = new javax.swing.JButton();
        SemuaTransaksiBtn = new javax.swing.JButton();
        tentangBtn = new javax.swing.JButton();
        dataAnalisBtn = new javax.swing.JButton();
        laporanSalesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("©PROJECT UAS PBD \"NASA-TEAM\"");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutBtn.setBackground(new java.awt.Color(0, 127, 152));
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sign_outBtn.png"))); // NOI18N
        LogoutBtn.setBorder(null);
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1010, 720));

        tambahStaffBtn.setBackground(new java.awt.Color(0, 127, 152));
        tambahStaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahStaffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/adduserBtn.png"))); // NOI18N
        tambahStaffBtn.setBorder(null);
        tambahStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahStaffBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tambahStaffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 40));

        tambahMobilBtn.setBackground(new java.awt.Color(22, 58, 82));
        tambahMobilBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tambahMobilBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahMobilBtn.setText("Tambah Mobil");
        tambahMobilBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tambahMobilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMobilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tambahMobilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 140, 40));

        pinjamMobilBtn.setBackground(new java.awt.Color(22, 58, 82));
        pinjamMobilBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pinjamMobilBtn.setForeground(new java.awt.Color(255, 255, 255));
        pinjamMobilBtn.setText("Pinjam Mobil");
        pinjamMobilBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pinjamMobilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamMobilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pinjamMobilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 140, 40));

        PengembalianMobilBtn.setBackground(new java.awt.Color(22, 58, 82));
        PengembalianMobilBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PengembalianMobilBtn.setForeground(new java.awt.Color(255, 255, 255));
        PengembalianMobilBtn.setText("Pengembalian Mobil");
        PengembalianMobilBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PengembalianMobilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengembalianMobilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PengembalianMobilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 140, 40));

        SemuaTransaksiBtn.setBackground(new java.awt.Color(22, 58, 82));
        SemuaTransaksiBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SemuaTransaksiBtn.setForeground(new java.awt.Color(255, 255, 255));
        SemuaTransaksiBtn.setText("Semua Transaksi");
        SemuaTransaksiBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SemuaTransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemuaTransaksiBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SemuaTransaksiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, 40));

        tentangBtn.setBackground(new java.awt.Color(22, 58, 82));
        tentangBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tentangBtn.setForeground(new java.awt.Color(255, 255, 255));
        tentangBtn.setText("!");
        tentangBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tentangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tentangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 70, 30));

        dataAnalisBtn.setBackground(new java.awt.Color(22, 58, 82));
        dataAnalisBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dataAnalisBtn.setForeground(new java.awt.Color(255, 255, 255));
        dataAnalisBtn.setText("Data Analisis");
        dataAnalisBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataAnalisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAnalisBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dataAnalisBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 140, 40));

        laporanSalesBtn.setBackground(new java.awt.Color(22, 58, 82));
        laporanSalesBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        laporanSalesBtn.setForeground(new java.awt.Color(255, 255, 255));
        laporanSalesBtn.setText("Laporan Sales");
        laporanSalesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laporanSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanSalesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(laporanSalesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 140, 40));

        namaLogin.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        namaLogin.setForeground(new java.awt.Color(255, 255, 255));
        namaLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/CekuserName.png"))); // NOI18N
        getContentPane().add(namaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroudBtn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // Button Logut
        dispose();
        Login fm = new Login();
        fm.setVisible(true);
        
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void tambahMobilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMobilBtnActionPerformed
        // Button Tambah Mobil
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        TambahMobil fm = new TambahMobil();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_tambahMobilBtnActionPerformed

    private void tambahStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahStaffBtnActionPerformed
        // Button Tambah Staff
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        TambahStaff fm = new TambahStaff();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_tambahStaffBtnActionPerformed

    private void pinjamMobilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamMobilBtnActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        PinjamMobil fm = new PinjamMobil();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_pinjamMobilBtnActionPerformed

    private void PengembalianMobilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengembalianMobilBtnActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        PengembalianMobil fm = new PengembalianMobil();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_PengembalianMobilBtnActionPerformed

    private void tentangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangBtnActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        TentangApp fm = new TentangApp();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_tentangBtnActionPerformed

    private void dataAnalisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAnalisBtnActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        LaporanAnalis fm = new LaporanAnalis();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_dataAnalisBtnActionPerformed

    private void laporanSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanSalesBtnActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        LaporanSales fm = new LaporanSales();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
    }//GEN-LAST:event_laporanSalesBtnActionPerformed

    private void SemuaTransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemuaTransaksiBtnActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        SemuaTransaksi fm = new SemuaTransaksi();
        fm.setVisible(true);
        jDesktopPane1.add(fm);
        
    }//GEN-LAST:event_SemuaTransaksiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton PengembalianMobilBtn;
    private javax.swing.JButton SemuaTransaksiBtn;
    private javax.swing.JButton dataAnalisBtn;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporanSalesBtn;
    public static final javax.swing.JLabel namaLogin = new javax.swing.JLabel();
    private javax.swing.JButton pinjamMobilBtn;
    private javax.swing.JButton tambahMobilBtn;
    private javax.swing.JButton tambahStaffBtn;
    private javax.swing.JButton tentangBtn;
    // End of variables declaration//GEN-END:variables


    public void Admin() {
       
        tambahStaffBtn.setVisible(true);
    }

    public void Staff() {
        
        tambahStaffBtn.setVisible(false);
    }
}
