/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author nameless
 */
public class LaporanAnalis extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public LaporanAnalis() {
        initComponents();
        //setVisible(True);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        barBtn = new javax.swing.JButton();
        lineBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pieBtn = new javax.swing.JButton();
        outputPenel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("DATA ANALIS RENTAL");
        getContentPane().setLayout(null);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(390, 80, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(530, 80, 440, 20);

        barBtn.setBackground(new java.awt.Color(204, 204, 204));
        barBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        barBtn.setForeground(new java.awt.Color(51, 51, 51));
        barBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/grafikBtn.png"))); // NOI18N
        barBtn.setText("Laporan Bulanan");
        barBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barBtnActionPerformed(evt);
            }
        });
        getContentPane().add(barBtn);
        barBtn.setBounds(40, 270, 190, 50);

        lineBtn.setBackground(new java.awt.Color(204, 204, 204));
        lineBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lineBtn.setForeground(new java.awt.Color(51, 51, 51));
        lineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/grafikBtn.png"))); // NOI18N
        lineBtn.setText("Laporan Mingguan");
        lineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lineBtn);
        lineBtn.setBounds(40, 210, 190, 50);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA GRAFIK");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 70, 190, 40);

        pieBtn.setBackground(new java.awt.Color(204, 204, 204));
        pieBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        pieBtn.setForeground(new java.awt.Color(51, 51, 51));
        pieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/grafikBtn.png"))); // NOI18N
        pieBtn.setText("Laporan Staff");
        pieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pieBtn);
        pieBtn.setBounds(40, 150, 190, 50);

        outputPenel.setBackground(new java.awt.Color(22, 58, 82));
        getContentPane().add(outputPenel);
        outputPenel.setBounds(290, 70, 680, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barBtnActionPerformed
        // TODO add your handling code here:
       outputPenel.removeAll();
       outputPenel.repaint();
       tampiBulanan();
    }//GEN-LAST:event_barBtnActionPerformed

    private void lineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineBtnActionPerformed
        // TODO add your handling code here:
        outputPenel.removeAll();
        outputPenel.repaint();
        tampilMingguan();
    }//GEN-LAST:event_lineBtnActionPerformed

    private void pieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieBtnActionPerformed
        // TODO add your handling code here:
        outputPenel.removeAll();
        outputPenel.repaint();
        tampilStaff();
    }//GEN-LAST:event_pieBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton lineBtn;
    private javax.swing.JPanel outputPenel;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton pieBtn;
    // End of variables declaration//GEN-END:variables

    public void tampiBulanan(){
         try {
            Connection koneksi = new KonekDB().getConnection();
            String query = "SELECT  to_char(tgl_sewa,'MONTH'), SUM(TOTAL)\n" +
                            "FROM tb_sewa\n" +
                            "WHERE tgl_sewa > SYSDATE - INTERVAL '2' MONTH \n" +
                            "GROUP BY to_char(tgl_sewa,'MONTH')" +
                            "ORDER BY TO_CHAR(tgl_sewa,'MONTH') ASC";
            Statement stat = koneksi.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            DefaultCategoryDataset cobaBar = new DefaultCategoryDataset();
			
            while (hasil.next()){

                cobaBar.setValue(hasil.getInt(2), hasil.getString(1),"");
            }
            koneksi.close();
			
            JFreeChart chart = ChartFactory.createBarChart3D("TOTAL SALES BULAN SEBELUMNYA", "BULAN", "TOTAL SALES", cobaBar, PlotOrientation.VERTICAL,true,true,false);

            ChartPanel panelCart = new ChartPanel(chart);
            outputPenel.add(panelCart);
            outputPenel.validate();
            outputPenel.updateUI();
            
			
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void tampilStaff(){
         try {
            Connection koneksi = new KonekDB().getConnection();
            String query = "SELECT DISTINCT pg.nama, COUNT(sw.ID_PEGAWAI)\n" +
                            "FROM tb_sewa sw, tb_pegawai pg\n" +
                            "WHERE sw.id_pegawai = pg.id_pegawai\n" +
                            "AND tgl_sewa > SYSDATE - INTERVAL '30' DAY\n" +
                            "GROUP BY pg.nama\n" +
                            "ORDER BY COUNT(sw.ID_PEGAWAI) DESC";
            Statement stat = koneksi.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            DefaultPieDataset cobaPie = new DefaultPieDataset();
			
            while (hasil.next()){
                cobaPie.setValue(hasil.getString(1), new Integer(hasil.getString(2)));
            }
            koneksi.close();
            
            JFreeChart chart = ChartFactory.createPieChart3D("STAFF HANDLE 30 HARI TERAKHIR", cobaPie, true, true, false);
            PiePlot piePlot = (PiePlot) chart.getPlot();

            ChartPanel panelCart = new ChartPanel(chart);
            outputPenel.add(panelCart);
            outputPenel.validate();
            outputPenel.updateUI();
            
			
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //==========================================================================
    public void tampilMingguan(){
         try {
            Connection koneksi = new KonekDB().getConnection();
            String query = "SELECT DISTINCT TO_CHAR(tgl_sewa), SUM(TOTAL)\n" +
                            "FROM tb_sewa\n" +
                            "WHERE tgl_sewa > SYSDATE - INTERVAL '14' DAY\n" +
                            "GROUP BY TO_CHAR(tgl_sewa)" +
                            "ORDER BY TO_CHAR(tgl_sewa) ASC";
            Statement stat = koneksi.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            DefaultCategoryDataset cobaLine = new DefaultCategoryDataset();
            
            while (hasil.next()){
                  cobaLine.setValue(hasil.getInt(2), "SALES NASA RENTAL", hasil.getString(1));
            }
            koneksi.close();        
            JFreeChart chart = ChartFactory.createLineChart3D("TOTAL SALES 2 MINGGU TERAKHIR", "TANGGAL", "SALES", cobaLine, PlotOrientation.VERTICAL, true,true,false);
            ChartPanel panelCart = new ChartPanel(chart);
            outputPenel.add(panelCart);
            outputPenel.validate();
            outputPenel.updateUI();
            
			
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}


