import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nameless
 */
public class PengembalianMobil extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public PengembalianMobil() {
        initComponents();
        waktu();
        comboBox();
        tampilTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();
        resetBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nopolCb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMerk = new javax.swing.JLabel();
        lblTglSewa = new javax.swing.JLabel();
        lblTglKembali = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblNoKtp = new javax.swing.JLabel();
        lblLama = new javax.swing.JLabel();
        lblIdSewa = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglHariIni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORM TAMBAH MOBIL");
        getContentPane().setLayout(null);

        simpanBtn.setBackground(new java.awt.Color(204, 204, 204));
        simpanBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(51, 51, 51));
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printBtn.png"))); // NOI18N
        simpanBtn.setText("Simpan & Cetak");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(simpanBtn);
        simpanBtn.setBounds(400, 340, 200, 40);

        TableMobil.setAutoCreateRowSorter(true);
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Nomer Telpon", "Type"
            }
        ));
        TableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMobil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 390, 980, 300);

        resetBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/resetBtn.png"))); // NOI18N
        resetBtn.setToolTipText("");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(940, 320, 40, 34);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("No Polisi     :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ID Sewa      :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, 20));

        nopolCb.setMaximumRowCount(20);
        nopolCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        nopolCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolCbActionPerformed(evt);
            }
        });
        jPanel2.add(nopolCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 155, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Tgl Sewa       :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Total Harga  :  Rp.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nama       :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Alamat     :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("No. Ktp    :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Merk           :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Tgl Kembali  :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 20));

        lblMerk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMerk.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 149, 20));

        lblTglSewa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglSewa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTglSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 165, 20));

        lblTglKembali.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglKembali.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 165, 20));

        lblNama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 190, 20));

        lblAlamat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 190, 20));

        lblNoKtp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoKtp.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblNoKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 190, 20));

        lblLama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 131, 40, 20));

        lblIdSewa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIdSewa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblIdSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 20));

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 150, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Lama           :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 110, 960, 200);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(20, 310, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(20, 310, 440, 20);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PENGEMBALIAN MOBIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 70, 330, 40);

        tglHariIni.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        tglHariIni.setForeground(new java.awt.Color(204, 204, 0));
        getContentPane().add(tglHariIni);
        tglHariIni.setBounds(790, 30, 200, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        nopolCb.setSelectedItem("Pilih");
        pesanBerhasil.setText(null);
        pesanGagal.setText(null);
        lblMerk.setText(null);
        lblLama.setText(null);
        lblIdSewa.setText(null);
        lblTglKembali.setText(null);
        lblTglSewa.setText(null);             
        lblTotal.setText(null);
        lblNama.setText(null);
        lblAlamat.setText(null);
        lblNoKtp.setText(null);
    }
    
    //TABLE Tampilakan
    private void tampilTransaksi(){
        Object[] header = {"NO.SEWA", "NO.PEGAWAI", "NO.POLISI", "TGL-PEMINJAMAN", "TLG-PENGEMBALIAN", "LAMA", "TOTAL HARGA"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_sewa ORDER BY tgl_sewa DESC";
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");
        
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String sewaId = hasil.getString("id_sewa");
                String pegawaiId = hasil.getString("id_pegawai");
                String nopol = hasil.getString("no_pol");
                String tglPeminjaman = sdf.format(hasil.getDate("tgl_sewa"));
                String tglPengembalian = sdf.format(hasil.getDate("tgl_kembali"));
                String lama = hasil.getString("lama");
                String total = hasil.getString("total");
                String[]data = {sewaId, pegawaiId, nopol, tglPeminjaman, tglPengembalian, lama, total};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
   
    
    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String uStatus="Tersedia";
        if(!"Pilih".equals(nopolCb.getSelectedItem().toString())) {
            pesanBerhasil.setText(null);
            pesanGagal.setText(null);
            try {
                Connection konek = new KonekDB().getConnection();
                String sql = "UPDATE tb_mobil SET "
                    + "status='"+uStatus+"'"
                    + "where no_pol='"+nopolCb.getSelectedItem().toString()+"'";
                PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
                stat.executeUpdate();
            
                konek.close();
                pesanBerhasil.setText("Mobil Telah Dikembalikan");
            
                //opsi print
                javax.swing.ImageIcon ico = new javax.swing.ImageIcon(getClass().getResource("/gambar/billing.png"));
                int jawab = JOptionPane.showConfirmDialog(this, "Apakah ingin cetak Bill..?", "Pilih Opsi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, ico);
            
                if(jawab == JOptionPane.YES_OPTION){
                    cetakBill();
                }
                dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            pesanGagal.setText("Silakan Pilih Plat Nomer");
        }
      
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void nopolCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolCbActionPerformed
        // TODO add your handling code here:
        tampilComboBox();
    }//GEN-LAST:event_nopolCbActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void TableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMobilMouseClicked
        
    }//GEN-LAST:event_TableMobilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdSewa;
    private javax.swing.JLabel lblLama;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoKtp;
    private javax.swing.JLabel lblTglKembali;
    private javax.swing.JLabel lblTglSewa;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JComboBox<String> nopolCb;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JLabel tglHariIni;
    // End of variables declaration//GEN-END:variables
        
    public void comboBox(){
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT no_pol FROM tb_mobil WHERE status='Terpakai'";
            ResultSet hasil = stat.executeQuery(sql);
            
            while(hasil.next()){
                nopolCb.addItem(hasil.getString(1));
            }
            hasil.close(); 
            stat.close();
            konek.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilComboBox(){
         try{
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT mb.MERK, sw.LAMA, sw.ID_SEWA, sw.TGL_SEWA, sw.TGL_KEMBALI,  sw.TOTAL,  pl.NAMA, pl.ALAMAT, pl.NO_KTP\n" +
                         "FROM TB_SEWA sw, TB_MOBIL mb, TB_PELANGGAN pl\n" +
                         "WHERE sw.NO_POL = mb.NO_POL\n" +
                         "AND sw.ID_SEWA = pl.ID_SEWA\n" +
                         "AND sw.TGL_KEMBALI >= SYSDATE\n" +
                         "AND mb.status = 'Terpakai'\n" +
                         "AND mb.NO_POL ='"+nopolCb.getSelectedItem()+"'";
            ResultSet hasil = stat.executeQuery(sql);
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");
            while (hasil.next()) {
                lblMerk.setText(hasil.getString(1));
                lblLama.setText(hasil.getString(2));
                lblIdSewa.setText(hasil.getString(3));
                lblTglSewa.setText(sdf.format(hasil.getDate(4)));             
                lblTglKembali.setText(sdf.format(hasil.getDate(5)));
                lblTotal.setText(hasil.getString(6));
                lblNama.setText(hasil.getString(7));
                lblAlamat.setText(hasil.getString(8));
                lblNoKtp.setText(hasil.getString(9));
            }
            hasil.close(); 
            stat.close();
            konek.close();
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }
    
    public void waktu() {
        Locale id = new Locale("in", "ID");
        Date hariIni = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy HH:mm:ss", id);
        tglHariIni.setText(sdf.format(hariIni));
    }
    
    //FUNGSI PRINT
    public void cetakBill() {
        try {
            KonekDB n = new KonekDB();
            HashMap<String, Object> para = new HashMap<String, Object>();
            para.put("param", Integer.parseInt(lblIdSewa.getText())); 
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("strukBill.jasper"), para, n.getConnection());
            JasperViewer.viewReport(jp, false);
            
        } catch (JRException e) {
            System.out.println(e.getMessage());
        }
    }
   
}        
     
    
