/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;
/**
 *
 * @author nameless
 */
public class PinjamMobil extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public PinjamMobil() {
        initComponents();
        //setVisible(True);
        idPelanggan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noKtpTxt = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JTextArea();
        teleponTxt = new javax.swing.JTextField();
        namaPeminjamTxt = new javax.swing.JTextField();
        batalBtn = new javax.swing.JButton();
        lanjutBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        noPelangganTxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORM DATA CUSTOMER");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("No. KTP     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 300, 90, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Alamat        :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 90, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("ID. Pelanggan   :  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 140, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Np. Telp     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 340, 100, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Nama          :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 90, 20);

        noKtpTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKtpTxtKeyTyped(evt);
            }
        });
        getContentPane().add(noKtpTxt);
        noKtpTxt.setBounds(130, 290, 240, 30);

        alamatTxt.setColumns(20);
        alamatTxt.setRows(5);
        getContentPane().add(alamatTxt);
        alamatTxt.setBounds(130, 220, 240, 60);

        teleponTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teleponTxtKeyTyped(evt);
            }
        });
        getContentPane().add(teleponTxt);
        teleponTxt.setBounds(130, 330, 240, 30);
        getContentPane().add(namaPeminjamTxt);
        namaPeminjamTxt.setBounds(130, 170, 240, 40);

        batalBtn.setBackground(new java.awt.Color(204, 204, 204));
        batalBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        batalBtn.setForeground(new java.awt.Color(51, 51, 51));
        batalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancelBtn.png"))); // NOI18N
        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(batalBtn);
        batalBtn.setBounds(120, 520, 110, 40);

        lanjutBtn.setBackground(new java.awt.Color(204, 204, 204));
        lanjutBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lanjutBtn.setForeground(new java.awt.Color(51, 51, 51));
        lanjutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/nextBtn.png"))); // NOI18N
        lanjutBtn.setText("Lanjutkan");
        lanjutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lanjutBtn);
        lanjutBtn.setBounds(240, 520, 120, 40);

        resetBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/resetBtn.png"))); // NOI18N
        resetBtn.setToolTipText("");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(60, 520, 40, 40);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(20, 370, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(20, 380, 440, 20);

        noPelangganTxt.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        noPelangganTxt.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(noPelangganTxt);
        noPelangganTxt.setBounds(150, 140, 50, 20);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM DATA PEMINJAM");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 70, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void idPelanggan(){
        
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT MAX(id_pelanggan) FROM tb_pelanggan";
            ResultSet hasil = stat.executeQuery(sql);
            
            if (hasil.next()) {
                String noPel = hasil.getString(1);
                String idPel = "" + (Integer.parseInt(noPel) + 1);

               noPelangganTxt.setText(idPel);
            } else {
               noPelangganTxt.setText("105");
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void reset(){
        //idTxt.setText(null);
        namaPeminjamTxt.setText(null);
        alamatTxt.setText(null);
        teleponTxt.setText(null);
        noKtpTxt.setText(null);
        pesanBerhasil.setText(null);
        pesanGagal.setText(null);
    }
    
    
    //BUTTON LANJUT
    private void lanjutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanjutBtnActionPerformed
        // TODO add your handling code here:
        if (namaPeminjamTxt.getText().isEmpty() ||
            alamatTxt.getText().isEmpty() || 
            teleponTxt.getText().isEmpty() ||
            noKtpTxt.getText().isEmpty()) { 
            pesanGagal.setText("Data Harus Lengkap..!!!");

        } else {
            String id = noPelangganTxt.getText();
            String nama = namaPeminjamTxt.getText();
            String alamat = alamatTxt.getText();
            String ktp = noKtpTxt.getText();
            String tlp = teleponTxt.getText();
            
            Home.jDesktopPane1.removeAll();
            Home.jDesktopPane1.repaint();
            TransaksiMobil fm = new TransaksiMobil(id, nama, alamat, ktp ,tlp);
            
            fm.setVisible(true);
            Home.jDesktopPane1.add(fm);
        }
        
    }//GEN-LAST:event_lanjutBtnActionPerformed
    
   
    //Button SIMPAN
    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_batalBtnActionPerformed

    private void teleponTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }else if (teleponTxt.getText().length() == 12) {
            evt.consume();
        }
    }//GEN-LAST:event_teleponTxtKeyTyped

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void noKtpTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKtpTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }else if (noKtpTxt.getText().length() == 16) {
            evt.consume();
        }
    }//GEN-LAST:event_noKtpTxtKeyTyped

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTxt;
    private javax.swing.JButton batalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lanjutBtn;
    private javax.swing.JTextField namaPeminjamTxt;
    private javax.swing.JTextField noKtpTxt;
    private javax.swing.JLabel noPelangganTxt;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField teleponTxt;
    // End of variables declaration//GEN-END:variables

    
}
