/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;
/**
 *
 * @author nameless
 */
public class TambahStaff extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public TambahStaff() {
        initComponents();
        //setVisible(True);
        tampilPegawai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JTextArea();
        teleponTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        namaStaffTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        typeCb = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pencarianBtn = new javax.swing.JButton();
        pencarianTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableStaff = new javax.swing.JTable();
        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORM TAMBAH STAFF");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("No. Telp     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 300, 90, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Alamat        :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 90, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Type           :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 420, 90, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("ID                 :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 90, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 340, 100, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Password  :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 380, 100, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Nama          :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 90, 20);
        getContentPane().add(usernameTxt);
        usernameTxt.setBounds(130, 330, 240, 30);

        alamatTxt.setColumns(20);
        alamatTxt.setRows(5);
        getContentPane().add(alamatTxt);
        alamatTxt.setBounds(130, 220, 240, 60);

        teleponTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teleponTxtKeyTyped(evt);
            }
        });
        getContentPane().add(teleponTxt);
        teleponTxt.setBounds(130, 290, 240, 30);

        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTxtKeyTyped(evt);
            }
        });
        getContentPane().add(idTxt);
        idTxt.setBounds(130, 130, 70, 30);
        getContentPane().add(namaStaffTxt);
        namaStaffTxt.setBounds(130, 170, 240, 40);
        getContentPane().add(passwordTxt);
        passwordTxt.setBounds(130, 370, 240, 30);

        typeCb.setBackground(new java.awt.Color(204, 204, 204));
        typeCb.setForeground(new java.awt.Color(51, 51, 51));
        typeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Admin" }));
        typeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCbActionPerformed(evt);
            }
        });
        getContentPane().add(typeCb);
        typeCb.setBounds(130, 420, 90, 24);

        simpanBtn.setBackground(new java.awt.Color(204, 204, 204));
        simpanBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(51, 51, 51));
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahBtn.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(simpanBtn);
        simpanBtn.setBounds(140, 520, 110, 40);

        ubahBtn.setBackground(new java.awt.Color(204, 204, 204));
        ubahBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ubahBtn.setForeground(new java.awt.Color(51, 51, 51));
        ubahBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ubahBtn.png"))); // NOI18N
        ubahBtn.setText("Ubah");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ubahBtn);
        ubahBtn.setBounds(20, 520, 100, 40);

        hapusBtn.setBackground(new java.awt.Color(204, 204, 204));
        hapusBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hapusBtn.setForeground(new java.awt.Color(51, 51, 51));
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapusBtn.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hapusBtn);
        hapusBtn.setBounds(260, 520, 110, 40);

        resetBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/resetBtn.png"))); // NOI18N
        resetBtn.setToolTipText("");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(330, 410, 40, 40);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 51), null, null, new java.awt.Color(255, 51, 51)));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 35));

        pencarianBtn.setBackground(new java.awt.Color(204, 204, 204));
        pencarianBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pencarian.png"))); // NOI18N
        pencarianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianBtnActionPerformed(evt);
            }
        });

        pencarianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianTxtActionPerformed(evt);
            }
        });
        pencarianTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pencarianTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pencarianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pencarianTxt)
                    .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 120, 580, 40);

        TableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStaffMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableStaff);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 183, 580, 380);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(400, 570, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(400, 570, 440, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("#Tulis Nama Staff yand dicari...!!!");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 160, 180, 15);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM TAMBAH STAFF");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 70, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        idTxt.setText(null);
        namaStaffTxt.setText(null);
        alamatTxt.setText(null);
        teleponTxt.setText(null);
        usernameTxt.setText(null);
        passwordTxt.setText(null);
        typeCb.setSelectedItem(this);
        pencarianTxt.setText(null);
        pesanBerhasil.setText(null);
        pesanGagal.setText(null);
    }
    
    //TABLE Tampilakan
    private void tampilPegawai(){
        Object[] header = {"ID PEGAWAI", "NAMA", "ALAMAT", "NO. TELPON"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableStaff.setModel(tabmode);
        String sql = "SELECT * FROM tb_pegawai";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id = hasil.getString("id_pegawai");
                String nama = hasil.getString("nama");
                String alamat = hasil.getString("alamat");
                String no_telpon = hasil.getString("no_telpon");
                String[]data = {id, nama, alamat, no_telpon};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //BUTTON HAPUS
    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        String id="";
        id = idTxt.getText();
        try {
        Connection konek = new KonekDB().getConnection();
        String sql = "DELETE FROM tb_pegawai WHERE id_pegawai='"+id+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            tampilPegawai();
            reset();
            konek.close();
            pesanBerhasil.setText("Data Berhasil Dihapus..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Gagal Dihapus..!!!");
        }     
    }//GEN-LAST:event_hapusBtnActionPerformed
    
    //Button PENCARIAN
    private void pencarianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianBtnActionPerformed
        // TODO add your handling code here:
        Object[] header = {"ID PEGAWAI", "NAMA", "ALAMAT", "NO. TELPON"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableStaff.setModel(tabmode);
        String sql = "SELECT * FROM tb_pegawai WHERE nama LIKE '%"+pencarianTxt.getText()+"%'";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id = hasil.getString("id_pegawai");
                String nama = hasil.getString("nama");
                String alamat = hasil.getString("alamat");
                String no_telpon = hasil.getString("no_telpon");
                String[]data = {id, nama, alamat, no_telpon};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
            pesanGagal.setText("Data Tidak Ditemukan..!!!");
        }
        
    }//GEN-LAST:event_pencarianBtnActionPerformed
    
    //Button SIMPAN
    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String id_pegawai="", nama= "", alamat= "", no_telpon= "", username= "", password ="", type="";
              
        id_pegawai = idTxt.getText();
        nama = namaStaffTxt.getText(); 
        alamat = alamatTxt.getText();
        no_telpon = teleponTxt.getText();
        username = usernameTxt.getText();
        password = passwordTxt.getText();
        type = typeCb.getSelectedItem().toString();

        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "INSERT INTO tb_pegawai VALUES ('"+id_pegawai+"','"+ nama +"','"+ alamat +"','"+ no_telpon +"','"+ username +"','"+ password +"','"+ type +"')";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            reset();
            konek.close();
            tampilPegawai();
            pesanBerhasil.setText("Data Berhasil Disimpan..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Gagal Disimpan..!!!");
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void teleponTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teleponTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_teleponTxtKeyTyped

    private void idTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_idTxtKeyTyped

    private void TableStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStaffMouseClicked
        // TODO add your handling code here:
            try {
            int J_Table1 = TableStaff.getSelectedRow();
        
            idTxt.setText(TableStaff.getValueAt(J_Table1, 0).toString());
            namaStaffTxt.setText(TableStaff.getValueAt(J_Table1, 1).toString());
            alamatTxt.setText(TableStaff.getValueAt(J_Table1, 2).toString());
            teleponTxt.setText(TableStaff.getValueAt(J_Table1, 3).toString());
        
            Connection konek = new KonekDB().getConnection();
             
            String sql = "SELECT * FROM tb_pegawai WHERE id_pegawai='"+idTxt+"'";
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
                while (hasil.next()){
                    usernameTxt.setText(hasil.getString("username"));
                    passwordTxt.setText(hasil.getString("password"));
                    typeCb.setSelectedItem(hasil.getString("type"));
                    }
            
            konek.close();
            } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
         
            
    }//GEN-LAST:event_TableStaffMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
        tampilPegawai();
    }//GEN-LAST:event_resetBtnActionPerformed

    //BUTTON UBAH
    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
        // TODO add your handling code here:
        String ID="", NAMA="", ALAMAT = "", NO_TELP = "";
        ID = idTxt.getText();
        NAMA = namaStaffTxt.getText();
        ALAMAT = alamatTxt.getText();
        NO_TELP = teleponTxt.getText();
        
        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "UPDATE tb_pegawai SET "
                    + "nama='"+NAMA+"',"
                    + "alamat='"+ALAMAT+"',"
                    + "no_telpon='"+NO_TELP+"'"
                    + "where id_pegawai='"+ID+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            tampilPegawai();
            reset();
            konek.close();
            pesanBerhasil.setText("Data Berhasil Diubah..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Gagal Diubah..!!!");
        }
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void pencarianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianTxtActionPerformed

    private void typeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeCbActionPerformed

    private void pencarianTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_pencarianTxtKeyTyped
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStaff;
    private javax.swing.JTextArea alamatTxt;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField namaStaffTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton pencarianBtn;
    private javax.swing.JTextField pencarianTxt;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField teleponTxt;
    private javax.swing.JComboBox<String> typeCb;
    private javax.swing.JButton ubahBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
