
import com.sun.beans.editors.IntegerEditor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nameless
 */
public class TambahMobil extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public TambahMobil() {
        initComponents();
        //setVisible(True);
        tampilMobil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nopolTxt = new javax.swing.JTextField();
        warnaTxt = new javax.swing.JTextField();
        merkTxt = new javax.swing.JTextField();
        hargaSewaTxt = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        statusCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();
        resetBtn = new javax.swing.JButton();
        tahunprodTxt = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        pencarianBtn = new javax.swing.JButton();
        pencarianTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORM TAMBAH MOBIL");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tahun Prod    :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 320, 120, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Warna Mobil  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 120, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Status              :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 370, 120, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Merk                :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 110, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("No. Polisi        :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 120, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Rp.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 280, 40, 20);
        getContentPane().add(nopolTxt);
        nopolTxt.setBounds(140, 220, 240, 30);
        getContentPane().add(warnaTxt);
        warnaTxt.setBounds(140, 170, 240, 30);
        getContentPane().add(merkTxt);
        merkTxt.setBounds(140, 120, 240, 30);

        hargaSewaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSewaTxtActionPerformed(evt);
            }
        });
        hargaSewaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaSewaTxtKeyTyped(evt);
            }
        });
        getContentPane().add(hargaSewaTxt);
        hargaSewaTxt.setBounds(170, 270, 210, 30);

        simpanBtn.setBackground(new java.awt.Color(204, 204, 204));
        simpanBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(51, 51, 51));
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahBtn.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(simpanBtn);
        simpanBtn.setBounds(140, 520, 110, 40);

        ubahBtn.setBackground(new java.awt.Color(204, 204, 204));
        ubahBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ubahBtn.setForeground(new java.awt.Color(51, 51, 51));
        ubahBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ubahBtn.png"))); // NOI18N
        ubahBtn.setText("Ubah");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ubahBtn);
        ubahBtn.setBounds(20, 520, 100, 40);

        hapusBtn.setBackground(new java.awt.Color(204, 204, 204));
        hapusBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hapusBtn.setForeground(new java.awt.Color(51, 51, 51));
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapusBtn.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hapusBtn);
        hapusBtn.setBounds(260, 520, 110, 40);

        statusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Terpakai" }));
        getContentPane().add(statusCb);
        statusCb.setBounds(140, 370, 100, 24);

        TableMobil.setAutoCreateRowSorter(true);
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Nomer Telpon", "Type"
            }
        ));
        TableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMobil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 190, 580, 370);

        resetBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/resetBtn.png"))); // NOI18N
        resetBtn.setToolTipText("");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(340, 360, 40, 40);
        getContentPane().add(tahunprodTxt);
        tahunprodTxt.setBounds(140, 320, 80, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 51), null, null, new java.awt.Color(255, 51, 51)));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 35));

        pencarianBtn.setBackground(new java.awt.Color(204, 204, 204));
        pencarianBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pencarian.png"))); // NOI18N
        pencarianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianBtnActionPerformed(evt);
            }
        });

        pencarianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianTxtActionPerformed(evt);
            }
        });
        pencarianTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pencarianTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pencarianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pencarianTxt)
                    .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 120, 580, 40);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("#Tulis Merk Mobil yang dicari...!!!");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 160, 180, 15);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(400, 570, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(400, 570, 440, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Harga Sewa  :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 110, 20);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM TAMBAH MOBIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 70, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        merkTxt.setText(null);
        warnaTxt.setText(null);
        nopolTxt.setText(null);
        hargaSewaTxt.setText(null);
        statusCb.setSelectedItem(this);
        pencarianTxt.setText(null);
        pesanBerhasil.setText(null);
        pesanGagal.setText(null);
    }
    
    public void tampilMobil(){
        Object[] header = {"NO POLISI", "MERK", "TAHUN", "WARNA", "HARGA", "STATUS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_mobil";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_pol = hasil.getString("no_pol");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String warna = hasil.getString("warna");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[]data = {no_pol, merk, tahun, warna, harga, status};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //BUTTON HAPUS
    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here
        String no="";
        no = nopolTxt.getText();
        try {
        Connection konek = new KonekDB().getConnection();
        String sql = "DELETE FROM tb_mobil WHERE no_pol ='"+no+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            tampilMobil();
            reset();
            konek.close();
            pesanBerhasil.setText("Data Berhasil Dihapus..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Gagal Dihapus..!!!");
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nopol="", merk= "", tahun= "", warna= "", harga= "", status="";
        
        
        nopol = nopolTxt.getText();
        merk = merkTxt.getText(); 
        warna = warnaTxt.getText();
        harga = hargaSewaTxt.getText();
        status = statusCb.getSelectedItem().toString();
        int y = tahunprodTxt.getYear();
        tahun = Integer.toString(y);

        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "INSERT INTO tb_mobil VALUES ('"+nopol+"','"+merk+"','"+tahun+"','"+warna+"','"+harga+"','"+status+"')";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            reset();
            konek.close();
            tampilMobil();
            pesanBerhasil.setText("Data Mobil Berhasil Disimpan..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Mobil Gagal Disimpan..!!!");
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
        tampilMobil();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void hargaSewaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSewaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSewaTxtActionPerformed

    private void hargaSewaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaSewaTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_hargaSewaTxtKeyTyped

    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
        // TODO add your handling code here:
        String nopol="", merk= "", tahun= "", warna= "", harga= "", status="";
        nopol = nopolTxt.getText();
        merk = merkTxt.getText(); 
        warna = warnaTxt.getText();
        harga = hargaSewaTxt.getText();
        status = statusCb.getSelectedItem().toString();
        int y = tahunprodTxt.getYear();
        tahun = Integer.toString(y);
        
        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "UPDATE tb_mobil SET "
                    + "merk='"+merk+"',"
                    + "tahun='"+tahun+"',"
                    + "warna='"+warna+"',"
                    + "harga='"+harga+"',"
                    + "status='"+status+"'"
                    + "where no_pol='"+nopol+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            tampilMobil();
            reset();
            konek.close();
            pesanBerhasil.setText("Data Berhasil Diubah..!!!");
        } catch (Exception e) {
            pesanGagal.setText("Data Gagal Diubah..!!!");
        }
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void TableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMobilMouseClicked
        // TODO add your handling code here:
        int J_Table1 = TableMobil.getSelectedRow();
        
            nopolTxt.setText(TableMobil.getValueAt(J_Table1, 0).toString());
            merkTxt.setText(TableMobil.getValueAt(J_Table1, 1).toString());
            tahunprodTxt.setYear(Integer.parseInt(TableMobil.getValueAt(J_Table1, 2).toString()));
            warnaTxt.setText(TableMobil.getValueAt(J_Table1, 3).toString());
            hargaSewaTxt.setText(TableMobil.getValueAt(J_Table1, 4).toString());
            statusCb.setSelectedItem(TableMobil.getValueAt(J_Table1, 5).toString());
    }//GEN-LAST:event_TableMobilMouseClicked

    private void pencarianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianBtnActionPerformed
        // TODO add your handling code here:
        Object[] header =  {"NO POLISI", "MERK", "TAHUN", "WARNA", "HARGA", "STATUS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_mobil WHERE merk LIKE '%"+pencarianTxt.getText()+"%'";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil == null){
                    pesanGagal.setText("Data Tidak Ditemukan..!!!");
            }
            while (hasil.next()){
                String no_pol = hasil.getString("no_pol");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String warna = hasil.getString("warna");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[]data = {no_pol, merk, tahun, warna, harga, status};
                tabmode.addRow(data);
            }
            
            konek.close();
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_pencarianBtnActionPerformed

    private void pencarianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianTxtActionPerformed

    private void pencarianTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_pencarianTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMobil;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField hargaSewaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField merkTxt;
    private javax.swing.JTextField nopolTxt;
    private javax.swing.JButton pencarianBtn;
    private javax.swing.JTextField pencarianTxt;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> statusCb;
    private com.toedter.calendar.JYearChooser tahunprodTxt;
    private javax.swing.JButton ubahBtn;
    private javax.swing.JTextField warnaTxt;
    // End of variables declaration//GEN-END:variables

}
