/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nameless
 */
public class TentangApp extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
   
    public TentangApp() {
        initComponents();
        //setVisible(True);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("TENTANG APLIKASI");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        //Redirect to image
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kelompok.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
