import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.KonekDB;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nameless
 */
public class TransaksiMobil extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TambahStaff
     */
    public TransaksiMobil(String id, String nama, String alamat, String ktp, String tlp) {
        initComponents();
        noSewa();
        noPegawai();
        waktu();
        comboBox();
        tampilMobil();
        //setVisible(True);
        lblIdpelanggan.setText(id);
        lblNama.setText(nama);
        lblAlamat.setText(alamat);
        lblKtp.setText(ktp);
        lblTlp.setText(tlp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();
        resetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pencarianBtn = new javax.swing.JButton();
        pencarianTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nopolCb = new javax.swing.JComboBox<>();
        lblMerk = new javax.swing.JLabel();
        lblThn = new javax.swing.JLabel();
        lblHrg = new javax.swing.JLabel();
        lblWrn = new javax.swing.JLabel();
        lblSts = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalHrg = new javax.swing.JLabel();
        lamaSpinner = new javax.swing.JSpinner();
        DealCb = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        tglKembaliTxt = new javax.swing.JLabel();
        tglPeminjaman = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblIdpelanggan = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblTlp = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKtp = new javax.swing.JLabel();
        pesanBerhasil = new javax.swing.JLabel();
        pesanGagal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglHariIni = new javax.swing.JLabel();
        noSewaTxt = new javax.swing.JLabel();
        noPegawaiTxt = new javax.swing.JLabel();
        noSewaTxt1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("FORM TAMBAH MOBIL");
        getContentPane().setLayout(null);

        simpanBtn.setBackground(new java.awt.Color(204, 204, 204));
        simpanBtn.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(51, 51, 51));
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambahBtn.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(simpanBtn);
        simpanBtn.setBounds(160, 320, 160, 40);

        TableMobil.setAutoCreateRowSorter(true);
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Nomer Telpon", "Type"
            }
        ));
        TableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMobil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 980, 300);

        resetBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/resetBtn.png"))); // NOI18N
        resetBtn.setToolTipText("");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(330, 320, 40, 40);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 51), null, null, new java.awt.Color(255, 51, 51)));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 35));

        pencarianBtn.setBackground(new java.awt.Color(204, 204, 204));
        pencarianBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pencarian.png"))); // NOI18N
        pencarianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianBtnActionPerformed(evt);
            }
        });

        pencarianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianTxtActionPerformed(evt);
            }
        });
        pencarianTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pencarianTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pencarianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pencarianTxt)
                    .addComponent(pencarianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(390, 320, 580, 40);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("No Polisi    :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Merk           :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Tahun         :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Warna        :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Status        :");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Harga         :");

        nopolCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih NO.POLISI-" }));
        nopolCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolCbActionPerformed(evt);
            }
        });

        lblMerk.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblMerk.setForeground(new java.awt.Color(255, 255, 255));

        lblThn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblThn.setForeground(new java.awt.Color(255, 255, 255));

        lblHrg.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblHrg.setForeground(new java.awt.Color(255, 255, 255));

        lblWrn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblWrn.setForeground(new java.awt.Color(255, 255, 255));

        lblSts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSts.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(lblThn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWrn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nopolCb, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nopolCb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThn, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(lblSts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 100, 330, 190);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Tgl Peminjaman     :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 116, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Setujuh");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Lama Pinjaman      :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 116, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Hari");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 43, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Total Harga : ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, 20));

        lblTotalHrg.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblTotalHrg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblTotalHrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 139, 135, 39));

        lamaSpinner.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lamaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        jPanel3.add(lamaSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 47, 30));

        DealCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealCbActionPerformed(evt);
            }
        });
        jPanel3.add(DealCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Rp.");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 139, -1, 39));

        tglKembaliTxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tglKembaliTxt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(tglKembaliTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, 20));

        tglPeminjaman.setName("tglPeminjaman"); // NOI18N
        jPanel3.add(tglPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Tgl Pengembalian  :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 116, 20));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(680, 100, 310, 190);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("ID. Pelanggan   :");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Nama          :");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Alamat        :");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("No. KTP       :");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("No. Telpon  :");

        lblIdpelanggan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblIdpelanggan.setForeground(new java.awt.Color(255, 255, 255));

        lblAlamat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));

        lblTlp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTlp.setForeground(new java.awt.Color(255, 255, 255));

        lblNama.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));

        lblKtp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblKtp.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdpelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTlp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblIdpelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTlp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 100, 300, 190);

        pesanBerhasil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanBerhasil.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(pesanBerhasil);
        pesanBerhasil.setBounds(10, 290, 440, 20);

        pesanGagal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesanGagal.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(pesanGagal);
        pesanGagal.setBounds(10, 290, 440, 20);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM SEWA MOBIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 60, 260, 40);

        tglHariIni.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        tglHariIni.setForeground(new java.awt.Color(204, 204, 0));
        getContentPane().add(tglHariIni);
        tglHariIni.setBounds(790, 30, 200, 20);

        noSewaTxt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noSewaTxt.setForeground(new java.awt.Color(231, 76, 61));
        getContentPane().add(noSewaTxt);
        noSewaTxt.setBounds(920, 80, 70, 20);

        noPegawaiTxt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noPegawaiTxt.setForeground(new java.awt.Color(231, 76, 61));
        getContentPane().add(noPegawaiTxt);
        noPegawaiTxt.setBounds(970, 80, 30, 20);

        noSewaTxt1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noSewaTxt1.setForeground(new java.awt.Color(255, 255, 255));
        noSewaTxt1.setText("No.Sewa:");
        getContentPane().add(noSewaTxt1);
        noSewaTxt1.setBounds(870, 80, 50, 20);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("#Tulis Merk Mobil yang dicari...!!!");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(390, 360, 180, 15);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundFr.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        tglKembaliTxt.setText(null);
        tglPeminjaman.setCalendar(null);
        DealCb.setSelected(false);
        lblTotalHrg.setText(null);
        pencarianTxt.setText(null);
        pesanBerhasil.setText(null);
        pesanGagal.setText(null);
        lamaSpinner.setValue(1);
        nopolCb.setSelectedItem("-");
        
    }
    
    //TABLE Tampilakan
    private void tampilTransaksi(){
        Object[] header = {"NO.SEWA", "NO.PEGAWAI", "NO.POLISI", "TGL-PEMINJAMAN", "TLG-PENGEMBALIAN", "LAMA", "TOTAL HARGA"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_sewa ORDER BY tgl_sewa DESC";
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy");
        
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String sewaId = hasil.getString("id_sewa");
                String pegawaiId = hasil.getString("id_pegawai");
                String nopol = hasil.getString("no_pol");
                String tglPeminjaman = sdf.format(hasil.getDate("tgl_sewa"));
                String tglPengembalian = sdf.format(hasil.getDate("tgl_kembali"));
                String lama = hasil.getString("lama");
                String total = hasil.getString("total");
                String[]data = {sewaId, pegawaiId, nopol, tglPeminjaman, tglPengembalian, lama, total};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void tampilMobil(){
        Object[] header = {"NO POLISI", "MERK", "TAHUN", "WARNA", "HARGA", "STATUS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_mobil ORDER BY tahun ASC";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_pol = hasil.getString("no_pol");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String warna = hasil.getString("warna");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[]data = {no_pol, merk, tahun, warna, harga, status};
                tabmode.addRow(data);
            }
            konek.close();
        } catch (Exception e) {
        //    JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            
            if (DealCb.isSelected()) {
                if (!cekMobil()) {
                    pesanGagal.setText("Mobil Dipakai Dan Belum Kembali");
                } else {
                    String idSewa="", idPegawai= "", nopol= "", lama="", total="";
     
                    idSewa = noSewaTxt.getText();
                    idPegawai = noPegawaiTxt.getText();
                    nopol = nopolCb.getSelectedItem().toString();
                    lama = lamaSpinner.getValue().toString();
                    total = lblTotalHrg.getText();

                    java.util.Date tglSw = tglPeminjaman.getDate();
                    SimpleDateFormat df = new SimpleDateFormat("dd-MMM-yyyy"); 
                    String tglSewa = df.format(tglSw);
                    String tglKembali = tglKembaliTxt.getText();

                    Connection konek = new KonekDB().getConnection();
                    String sql = "INSERT INTO tb_sewa VALUES ('"+idSewa+"','"+idPegawai+"','"+nopol+"','"+tglSewa+"','"+tglKembali+"','"+lama+"','"+total+"')";
                    PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
                    stat.executeUpdate();
            
                    konek.close();
                    dataPeminjam();
                    dataMobil();
                    reset();
                    tampilTransaksi();
                    
                    pesanBerhasil.setText("Transaksi Berhasil..!!!");
                }
            } else {
                pesanGagal.setText("Centang Untuk Selesaikan Transaksi");
            }       
        } catch (Exception e) {
            System.out.println(e.getMessage());
//            pesanGagal.setText("Transaksi Gagal..!!!");
        }
        
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void TableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMobilMouseClicked
        // TODO add your handling code here:
        int J_Table1 = TableMobil.getSelectedRow();
        
//            nopolTxt.setText(TableMobil.getValueAt(J_Table1, 0).toString());
//            merkTxt.setText(TableMobil.getValueAt(J_Table1, 1).toString());
//            //tahunprodTxt.setText(TableMobil.getValueAt(J_Table1, 2).toString());
//            warnaTxt.setText(TableMobil.getValueAt(J_Table1, 3).toString());
//            hargaSewaTxt.setText(TableMobil.getValueAt(J_Table1, 4).toString());
//            //statusCb.setText(TableMobil.getValueAt(J_Table1, 5).toString());
    }//GEN-LAST:event_TableMobilMouseClicked

    private void pencarianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianBtnActionPerformed
        // TODO add your handling code here:
        Object[] header =  {"NO POLISI", "MERK", "TAHUN", "WARNA", "HARGA", "STATUS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, header);
        TableMobil.setModel(tabmode);
        String sql = "SELECT * FROM tb_mobil WHERE merk LIKE '%"+pencarianTxt.getText()+"%'";
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil == null){
                    pesanGagal.setText("Data Tidak Ditemukan..!!!");
            }
            while (hasil.next()){
                String no_pol = hasil.getString("no_pol");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String warna = hasil.getString("warna");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[]data = {no_pol, merk, tahun, warna, harga, status};
                tabmode.addRow(data);
            }
            
            konek.close();
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_pencarianBtnActionPerformed

    private void pencarianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianTxtActionPerformed

    private void pencarianTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianTxtKeyTyped
        // TODO add your handling code here:
        if (!Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_pencarianTxtKeyTyped

    private void nopolCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolCbActionPerformed
        // TODO add your handling code here:
        tampilComboBox();
    }//GEN-LAST:event_nopolCbActionPerformed

    private void DealCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DealCbActionPerformed
        // TODO add your handling code here:
        if (DealCb.isSelected()) {
            hitungSelisih();
            
        } else {
            pesanGagal.setText(null);
        }
    }//GEN-LAST:event_DealCbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DealCb;
    private javax.swing.JTable TableMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JSpinner lamaSpinner;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblHrg;
    private javax.swing.JLabel lblIdpelanggan;
    private javax.swing.JLabel lblKtp;
    private javax.swing.JLabel lblMerk;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSts;
    private javax.swing.JLabel lblThn;
    private javax.swing.JLabel lblTlp;
    private javax.swing.JLabel lblTotalHrg;
    private javax.swing.JLabel lblWrn;
    public static javax.swing.JLabel noPegawaiTxt;
    private javax.swing.JLabel noSewaTxt;
    private javax.swing.JLabel noSewaTxt1;
    private javax.swing.JComboBox<String> nopolCb;
    private javax.swing.JButton pencarianBtn;
    private javax.swing.JTextField pencarianTxt;
    private javax.swing.JLabel pesanBerhasil;
    private javax.swing.JLabel pesanGagal;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JLabel tglHariIni;
    private javax.swing.JLabel tglKembaliTxt;
    private com.toedter.calendar.JDateChooser tglPeminjaman;
    // End of variables declaration//GEN-END:variables

    public void dataPeminjam() {
        String idSewa="", idPegawai= "", nama= "", alamat= "", noKTP= "", noTelp="";
     
        idSewa = noSewaTxt.getText();
        idPegawai = lblIdpelanggan.getText(); 
        nama = lblNama.getText();
        alamat = lblAlamat.getText();
        noTelp = lblTlp.getText();
        noKTP = lblKtp.getText();

        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "INSERT INTO tb_pelanggan VALUES ('"+idSewa+"','"+idPegawai+"','"+nama+"','"+alamat+"','"+noTelp+"','"+noKTP+"')";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            konek.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
      
    }
    
    public void dataMobil() {
        String uStatus="Terpakai";
        
        try {
            Connection konek = new KonekDB().getConnection();
            String sql = "UPDATE tb_mobil SET "
                    + "status='"+uStatus+"'"
                    + "where no_pol='"+nopolCb.getSelectedItem().toString()+"'";
            PreparedStatement stat = (PreparedStatement) konek.prepareStatement(sql);
            stat.executeUpdate();
            
            konek.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
      
    }
    
    
    public void comboBox(){
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT no_pol FROM tb_mobil";
            ResultSet hasil = stat.executeQuery(sql);
            
            while(hasil.next()){
                Object[] ob = new Object[1];
                ob[0] = hasil.getString(1);
                nopolCb.addItem((String) ob[0]);
            }
            hasil.close(); 
            stat.close();
            konek.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilComboBox(){
        try{
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT * FROM tb_mobil WHERE no_pol='"+nopolCb.getSelectedItem()+"'";
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                lblMerk.setText(hasil.getString("merk"));
                lblThn.setText(hasil.getString("tahun"));
                lblWrn.setText(hasil.getString("warna"));
                lblHrg.setText(hasil.getString("harga"));
                lblSts.setText(hasil.getString("status"));
            }
			
            hasil.close(); 
            stat.close();
            konek.close();
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }
    
    public void hitungSelisih() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            Date saatIni = new Date();
            
            int lama_sewa = (int)lamaSpinner.getValue();
            Date tgl = tglPeminjaman.getDate();
            
            Calendar calTambah = Calendar.getInstance();

            calTambah.setTime(tgl);
            calTambah.add(Calendar.DAY_OF_MONTH, lama_sewa);
            tglKembaliTxt.setText(sdf.format(calTambah.getTime()));
            
            if(tgl.equals(saatIni)){
                pesanGagal.setText("Tanggal Peminjaman Sudah Melampaui..!!!");
            }else{
                int harga_sewa = Integer.parseInt(lblHrg.getText()); //Mengambil nilai hargaMobil di pars ke integer
                int Total = harga_sewa * lama_sewa;            //Menhitung total Harga
                String a = Integer.toString(Total);
                lblTotalHrg.setText(a);
            }
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    
    
    public void waktu() {
        Locale id = new Locale("in", "ID");
        String pattern = "EEEE, dd MMM yyyy HH:mm:ss";
        Date hariIni = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat(pattern, id);
        tglHariIni.setText(sdf.format(hariIni));
    }
    
    
    public void noSewa() {
        
        try {
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT MAX(id_sewa) FROM tb_sewa";
            ResultSet hasil = stat.executeQuery(sql);
            
            if (hasil.next()) {
                String noSew = hasil.getString(1);
                String idSew = "" + (Integer.parseInt(noSew) + 1);

               noSewaTxt.setText(idSew);
            } else {
               noSewaTxt.setText("2222215");
            }
            
            konek.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    public void noPegawai(){
        try{
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT * FROM tb_pegawai WHERE nama ='"+Home.namaLogin.getText()+"'";
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                noPegawaiTxt.setText(hasil.getString(1));
            }
            hasil.close(); 
            stat.close();
            konek.close();
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }
    
    public boolean cekMobil() {
        boolean cek = false;
        String status1 = "";
        try{
            Connection konek = new KonekDB().getConnection();
            Statement stat = konek.createStatement();
            String sql = "SELECT * FROM tb_mobil WHERE no_pol='"+nopolCb.getSelectedItem()+"'";
            ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
            status1 = hasil.getString("status");
            }
            
            if ( status1.equals("Terpakai")) {
            cek = false;
            } else {
            cek = true;
            }
        }
        catch(Exception e){
            System.out.print(e.getMessage());
    
        }
        return cek;
    }
    
}        
     
    
